services:
  api:
    build: ./app

    ports:
      - "8080:8080"

    environment:
      APP_VERSION: cloudsql-test
      DB_HOST: 10.160.80.3
      DB_PORT: "5432"
      DB_SSL: "true"
      DB_NAME: medirdv
      DB_USER: medirdv-app
      DB_PASSWORD_SECRET: projects/1068394158097/secrets/medirdv-db-password/versions/latest
      POOL_MAX: "5"
